services:
  db:
    image: postgres:15.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wO2VGDsMKR
    ports:
      - '5432:5432'
    networks:
      - pluggable-dapr
    volumes: 
      - db:/var/lib/postgresql/data
  pluggableapp:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pluggable-dapr
    volumes:
      - shared-volume:/tmp/dapr-components-sockets
    depends_on:
      - db
  pluggableapp-dapr:
    image: "daprio/daprd:1.13.0-rc.6"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: ["./daprd",
     "-app-id", "pluggableapp",
     "-dapr-http-port", "3500",
     "-resources-path", "/DaprComponents",
     "-log-level","debug"]
    volumes:
        - "./DaprComponents/:/DaprComponents"
        - shared-volume:/tmp/dapr-components-sockets
    depends_on:
      - pluggableapp
    ports:
      - "3500:3500"
    networks:
      - pluggable-dapr
volumes:
  shared-volume:
  db:
    driver: local
networks:
    pluggable-dapr: